'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useAppStore } from '@/store/useAppStore';
import { ArrowLeft, Download, FileText, Code, Database, Workflow, CheckCircle, Save } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import { generateSQL } from '@/lib/schema-utils';
import { toast } from '@/components/ui/use-toast';

function generateMarkdown(state: ReturnType<typeof useAppStore.getState>): string {
  const { optimizedData, workflowData, schemaData, databaseType, devEnvironment, projectType, originalIdea } = state;

  const envCommands: Record<string, string> = {
    'opencode': 'npm i -g opencode && opencode',
    'claude-terminal': 'npm i -g @anthropic-ai/claude-code && claude',
    'claude-vscode': 'Install Claude Code extension in VS Code',
    'claude-desktop': 'Open Claude Desktop and configure MCP',
    'gemini-antigraphity': 'Visit antigraphity.com',
  };

  return `# ${optimizedData?.appName || 'New Project'}

> ${optimizedData?.tagline || ''}

## Project Type
${projectType === 'personal' ? 'Personal Tool' : 'Public App'}

## Original Idea
${originalIdea}

## Description
${optimizedData?.description || ''}

## Core Features
${optimizedData?.features.map((f, i) => `${i + 1}. ${f}`).join('\n') || ''}

## Database
- Type: ${databaseType?.toUpperCase()}
- Tables: ${schemaData?.tables.map(t => t.name).join(', ') || ''}

## Quick Start

### 1. Set up your environment
\`\`\`bash
${envCommands[devEnvironment || 'opencode']}
\`\`\`

### 2. Paste this prompt
\`\`\`
Build me ${optimizedData?.appName}: ${optimizedData?.description}

Features:
${optimizedData?.features.map(f => `- ${f}`).join('\n')}

Use ${databaseType?.toUpperCase()} for the database.
\`\`\`

## Workflow Pipelines
${workflowData?.pipelines.map(p => `
### ${p.name}
${p.steps.map(s => `- **${s.name}** (${s.type}): ${s.description}`).join('\n')}
`).join('\n') || ''}

---
Generated by FlowForge Pro
`;
}

function generateN8NWorkflow(state: ReturnType<typeof useAppStore.getState>): object {
  const { workflowData, optimizedData } = state;

  return {
    name: optimizedData?.appName || 'New Workflow',
    nodes: workflowData?.pipelines.flatMap((pipeline, pIndex) =>
      pipeline.steps.map((step, sIndex) => ({
        id: step.id,
        name: step.name,
        type: `n8n-nodes-base.${step.type === 'start' ? 'start' : step.type === 'api' ? 'httpRequest' : step.type === 'database' ? 'postgres' : 'function'}`,
        position: [250 * sIndex, 100 * pIndex],
        parameters: {
          description: step.description,
        },
      }))
    ) || [],
    connections: workflowData?.pipelines.reduce((acc, pipeline) => {
      pipeline.connections.forEach(conn => {
        if (!acc[conn.from]) acc[conn.from] = { main: [[]] };
        acc[conn.from].main[0].push({ node: conn.to, type: 'main', index: 0 });
      });
      return acc;
    }, {} as Record<string, { main: { node: string; type: string; index: number }[][] }>) || {},
  };
}

function generateComfyUIWorkflow(state: ReturnType<typeof useAppStore.getState>): object {
  const { workflowData, optimizedData } = state;

  return {
    name: optimizedData?.appName || 'New Workflow',
    version: '1.0',
    nodes: workflowData?.pipelines.flatMap((pipeline, pIndex) =>
      pipeline.steps.map((step, sIndex) => ({
        id: parseInt(step.id.replace(/\D/g, '')) || sIndex + pIndex * 100,
        type: step.type,
        title: step.name,
        pos: [250 * sIndex, 150 * pIndex],
        widgets_values: [step.description],
      }))
    ) || [],
    links: workflowData?.pipelines.flatMap((pipeline, pIndex) =>
      pipeline.connections.map((conn, cIndex) => [
        cIndex + pIndex * 100,
        parseInt(conn.from.replace(/\D/g, '')) || 0,
        0,
        parseInt(conn.to.replace(/\D/g, '')) || 0,
        0,
        'DATA',
      ])
    ) || [],
  };
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportPanel() {
  const state = useAppStore();
  const { prevStep, optimizedData, schemaData, databaseType, reset, setError } = state;
  const [isSaving, setIsSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleDownloadMarkdown = () => {
    const content = generateMarkdown(state);
    downloadFile(content, `${optimizedData?.appName || 'project'}-devplan.md`, 'text/markdown');
    toast({
      title: 'Downloaded!',
      description: 'Development plan saved as Markdown',
      variant: 'success',
    });
  };

  const handleDownloadN8N = () => {
    const content = JSON.stringify(generateN8NWorkflow(state), null, 2);
    downloadFile(content, `${optimizedData?.appName || 'project'}-n8n.json`, 'application/json');
    toast({
      title: 'Downloaded!',
      description: 'N8N workflow exported successfully',
      variant: 'success',
    });
  };

  const handleDownloadComfyUI = () => {
    const content = JSON.stringify(generateComfyUIWorkflow(state), null, 2);
    downloadFile(content, `${optimizedData?.appName || 'project'}-comfyui.json`, 'application/json');
    toast({
      title: 'Downloaded!',
      description: 'ComfyUI workflow exported successfully',
      variant: 'success',
    });
  };

  const handleDownloadSQL = () => {
    const content = schemaData?.tables && databaseType
      ? generateSQL(schemaData.tables, databaseType)
      : '';
    downloadFile(content, `${optimizedData?.appName || 'project'}-schema.sql`, 'text/plain');
    toast({
      title: 'Downloaded!',
      description: 'SQL schema exported successfully',
      variant: 'success',
    });
  };

  const handleSaveProject = async () => {
    setIsSaving(true);
    setError(null);
    try {
      const response = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: uuidv4(),
          name: state.optimizedData?.appName || 'Untitled Project',
          projectType: state.projectType,
          originalIdea: state.originalIdea,
          optimizedData: state.optimizedData,
          workflowData: state.workflowData,
          schemaData: state.schemaData,
          devEnvironment: state.devEnvironment,
          databaseType: state.databaseType,
          status: 'completed',
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to save project');
      }

      setSaved(true);
      toast({
        title: 'Project Saved!',
        description: 'Your project has been saved to the database',
        variant: 'success',
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to save project';
      console.error('Error saving project:', error);
      setError(message);
      toast({
        title: 'Save Failed',
        description: message,
        variant: 'destructive',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleStartNew = () => {
    reset();
  };

  return (
    <div className="space-y-8">
      <div className="text-center">
        <h2 className="text-3xl font-bold bg-gradient-to-r from-cyan-400 to-magenta-400 bg-clip-text text-transparent">
          Export Your Project
        </h2>
        <p className="mt-2 text-muted-foreground">
          Download your project files and start building
        </p>
      </div>

      <Card className="gradient-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <CheckCircle className="h-5 w-5 text-green-400" />
            {optimizedData?.appName || 'Your Project'} is Ready!
          </CardTitle>
          <CardDescription>
            {optimizedData?.tagline}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline">{state.projectType === 'personal' ? 'Personal Tool' : 'Public App'}</Badge>
            <Badge variant="outline">{state.databaseType?.toUpperCase()}</Badge>
            <Badge variant="outline">{state.devEnvironment}</Badge>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-4 md:grid-cols-2">
        <Card className="cursor-pointer hover:border-primary/50 transition-colors" onClick={handleDownloadMarkdown}>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <FileText className="h-5 w-5 text-cyan-400" />
              Development Plan
            </CardTitle>
            <CardDescription>Complete Markdown guide with AI prompts</CardDescription>
          </CardHeader>
          <CardContent>
            <Button className="w-full gap-2">
              <Download className="h-4 w-4" />
              Download .md
            </Button>
          </CardContent>
        </Card>

        <Card className="cursor-pointer hover:border-primary/50 transition-colors" onClick={handleDownloadN8N}>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Workflow className="h-5 w-5 text-orange-400" />
              N8N Workflow
            </CardTitle>
            <CardDescription>Import into N8N automation platform</CardDescription>
          </CardHeader>
          <CardContent>
            <Button variant="secondary" className="w-full gap-2">
              <Download className="h-4 w-4" />
              Download .json
            </Button>
          </CardContent>
        </Card>

        <Card className="cursor-pointer hover:border-primary/50 transition-colors" onClick={handleDownloadComfyUI}>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Code className="h-5 w-5 text-purple-400" />
              ComfyUI Workflow
            </CardTitle>
            <CardDescription>Node-based workflow format</CardDescription>
          </CardHeader>
          <CardContent>
            <Button variant="outline" className="w-full gap-2">
              <Download className="h-4 w-4" />
              Download .json
            </Button>
          </CardContent>
        </Card>

        <Card className="cursor-pointer hover:border-primary/50 transition-colors" onClick={handleDownloadSQL}>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Database className="h-5 w-5 text-green-400" />
              SQL Schema
            </CardTitle>
            <CardDescription>CREATE TABLE statements</CardDescription>
          </CardHeader>
          <CardContent>
            <Button variant="outline" className="w-full gap-2">
              <Download className="h-4 w-4" />
              Download .sql
            </Button>
          </CardContent>
        </Card>
      </div>

      <div className="flex justify-between">
        <Button variant="outline" onClick={prevStep} className="gap-2">
          <ArrowLeft className="h-4 w-4" />
          Back
        </Button>
        <div className="flex gap-3">
          <Button
            variant="outline"
            onClick={handleSaveProject}
            disabled={isSaving || saved}
            className="gap-2"
          >
            {saved ? (
              <>
                <CheckCircle className="h-4 w-4 text-green-400" />
                Saved!
              </>
            ) : (
              <>
                <Save className="h-4 w-4" />
                {isSaving ? 'Saving...' : 'Save Project'}
              </>
            )}
          </Button>
          <Button onClick={handleStartNew} className="gap-2">
            Start New Project
          </Button>
        </div>
      </div>
    </div>
  );
}
